### ISSUE TITLE
The `copy_data_from` feature doesn't work on MySQL 8

### ISSUE THREAD

**Issue by Songmu** [kazuho/p5-test-mysqld#27]

**Comment by yoku0825** [comment]
This caused `--ignore-db-dir` is removed on MySQL 8.0.

https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html#mysql-nutshell-removals


In `--initialize` processing, unknown options are just ignored by mysqld (so, `copy_data_from` processing doesn't report this as "unknown variable").

**Comment by yoku0825** [comment]
And, MySQL 8.0 introduce new Data Dictionary.
`.frm` file is not used in new-DD, now `.sdi` file is created instead of `.frm` but this file has strong dependent to new-DD in `mysql.ibd` file.

**Comment by Songmu** [comment]
I know that. Even if we delete the `--ignore-data-dir` option, the following error will occur.

```
2018-07-19T13:39:48.694776Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
```

**Comment by Songmu** [comment]
https://github.com/kazuho/p5-test-mysqld/issues/27#issuecomment-406279826

Oh, thank you! I try to use them.

**Comment by yoku0825** [comment]
One way to solve this issue, 

- Copy `whole data-directory` which is initnialized by MySQL 8.0
- Run mysqld without any `--initialize*` option

**Comment by yoku0825** [comment]
Okay, initialization and caching_sha2_password.so and passed by this way.

```
$ /usr/mysql/8.0.11/bin/mysqld --initialize-insecure --lower_case_table_names=0 --datadir=/tmp/test_mysqld --default_authentication_plugin=mysql_native_password
$ cp -r /tmp/test_mysqld/{ibdata1,mysql,mysql.ibd,performance_schema,sys} t/05-copy-data-from/
$ perl t/05-copy-data-from.t
1..1
DBI connect('dbname=test;mysql_socket=/tmp/AyBA7T1Jmo/tmp/mysql.sock;user=root','',...) failed: Unknown database 'test' at t/05-copy-data-from.t line 21.
failed to connect to database:Unknown database 'test' at t/05-copy-data-from.t line 21.
# Looks like your test exited with -1 before it could output anything.
```
